### ISSUE TITLE
How to use with SSR

### ISSUE THREAD

**Issue by chapati23** [faceyspacey/redux-first-router-restore-scroll#12]
I'm building a project based on your fantastic redux-first-router-demo (thanks for that!) and am wondering how to make use of this package in an SSR context as the server obviously doesn't know about `window`

So if I just throw it in my `configureStore` like this:
```
  const {
    reducer,
    middleware,
    enhancer,
    thunk
  } = connectRoutes(history, routesMap, { restoreScroll: restoreScroll() })
```

express rightfully dies with `(node:56337) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): ReferenceError: window is not defined`

any pointers? do i need to split my `configureStore` into a client-side one _with_ scroll restoration and a server-side one _without_?

**Comment by faceyspacey** [comment]
Glad you found the demo useful. 

I don't suppose you have a bigger stack trace. I no promises usuallly lack them. This shouldn't be happening, but a quick fix doesn't even require another configure store file. Just do the typeof window check right there and only assign it if it's not undefined.

**Comment by chapati23** [comment]
ok, this gets me one error further:

```
const connectRoutesWithScrollRestoration = (history, routesMap) => {
  return typeof window !== 'undefined'
    ? connectRoutes(history, routesMap, {
        restoreScroll: restoreScroll()
      })
    : connectRoutes(history, routesMap)
}
```

Now it's dying in `shouldUpdateScroll`:
![image](https://user-images.githubusercontent.com/117495/28981898-fa319a88-7953-11e7-99e2-1bb885f0252c.png)

If I pass `manual: true` i don't get an error. but manual scroll restoration isn't really what i was hoping for :)

**Comment by chapati23** [comment]
Ok here's how I solved it for now:

```js
const connectRoutesWithScrollRestoration = (history, routesMap) => {
  return typeof window !== 'undefined'
    ? connectRoutes(history, routesMap, {
        restoreScroll: restoreScroll({
          shouldUpdateScroll: () => [0, 0]
        })
      })
    : connectRoutes(history, routesMap)
}
```

It's not really pretty, though. Especially if you make use of your `<Switcher>` component with that sweet 500ms page transition. The immediate scroll restoration makes the transition feel kinda janky.

Do you have this going in a real-world setup somewhere by any chance?

**Comment by faceyspacey** [comment]
Whatup brother, i won't be able to get back to you till tomorrow, been really busy with the launch of stuff in our other product line:

https://medium.com/faceyspacey/announcing-react-universal-component-2-0-babel-plugin-universal-import-5702d59ec1f4


...basically it's been a while since i've looked at the scroll restoration stuff and a few things have changed, so i gotta revisit it. That said, I really appreciate you taking the time with it, and I'll soon work very closely with you to make sure it works perfectly for you.


ps. the scroll restoration isnt really to be used in combination with the fixed position sliding style pages. it's more for basic webpages, but if thats what u need, we can do that too.

**Comment by chapati23** [comment]
no worries, man. it's open source after all :)

just trying to make myself a bit clearer. what i want is this:
![scroll restoration](https://user-images.githubusercontent.com/117495/28983459-222e4490-795a-11e7-8c44-ab50435d3d93.gif)

Just that on the 2nd page i want the scroll to happen automatically after the 500ms page transition is done: `Click Link => 500ms Page Transition => 200ms scrollRestoration => Boom`

**Comment by faceyspacey** [comment]
You know what you might really want is to put each "screen" in its own scrolling div, that way when they slide into place, they are always at the top (or where they were), and the wrong screen doesn't respond to the scroll restoration.

**Comment by chapati23** [comment]
Yeah, that could work. Would have to convert all top level components from stateless to classes because I guess I'd need to trigger the scrolling on `componentDidMount`

**Comment by faceyspacey** [comment]
yea. this should help: https://github.com/faceyspacey/redux-first-router-scroll-container

it's also not very hard to do manually once each component has its own.

...you also could just forget about the scrolling. as now, the next page will always appear at the top. so you'd only be worrying about when the user goes back. it wouldn't be the end of the world to get the first draft out, where if you go back it's at the top again. That's the main thing using independent scrolling divs automatically solves for you.

**Comment by aga5tya** [comment]
@faceyspacey, Is conditional **typeof window !== 'undefined'**, the only way to use the lib on server side or am i missing out some configuration ?

**Comment by faceyspacey** [comment]
not anymore:

https://github.com/faceyspacey/redux-first-router-restore-scroll/commit/5ab73a232e83fbebf848e7c83dfcc9127e5472fc

:)

should auto-publish to NPM soon. let me know if it doesnt.

**Comment by faceyspacey** [comment]
internally if nothing is returned RFR already knows not to use it.

**Comment by aga5tya** [comment]
Nice @faceyspacey,, is it gonna take long? its still 1.1.2,, thanks for the change 👍

**Comment by faceyspacey** [comment]
there was an eslint error. now it's fixed. check the top of the commits page for what travis is doing to see if it failed :)

**Comment by aga5tya** [comment]
@faceyspacey, my bad,, now travis seems to have built fine,, still no release tho ?

**Comment by faceyspacey** [comment]
tokens were old on travis. i updated the one i can get quickly. hopefully the other one doesnt need to to be updated to.

**Comment by faceyspacey** [comment]
its done
