### ISSUE TITLE
Check for permissions before use session storage

### ISSUE THREAD

**Issue by theonelucas** [faceyspacey/redux-first-router-restore-scroll#22]
When trying to use session storage, you should check first before access it to confirm that the browser has permission to use it, otherwise a error will be thrown:

![image](https://user-images.githubusercontent.com/5532541/39868058-58034be2-542e-11e8-9c0a-a00bf672c717.png)

I've gathered this error on a session whose browser had cookies disbled, and was able to reproduce it in chrome going to chrome://settings/content/cookies and disabling cookies.

**Comment by faceyspacey** [comment]
Ok we'll work this into the next major version of RFR called Rudy, which will have a new scroll restoration plugin

**Comment by theonelucas** [comment]
Ok, looking foward to it, thanks
